version: '3.8'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://...

  product-service:
    build: ./product-service
    ports:
      - "8001:8001"
